CREATE DATABASE courses_web;

\c courses_web

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level" varchar(15) NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(35) NOT NULL,
  "password" varchar(10) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(50) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "students_courses" (
  "student" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_categories" (
  "course_id" int NOT NULL,
  "category_id" int NOT NULL
);

ALTER TABLE "students_courses" ADD FOREIGN KEY ("student") REFERENCES "users" ("id");

ALTER TABLE "students_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

INSERT INTO roles (name) VALUES
('student'),
('teacher');

INSERT INTO users (name, email, password, age, rol_id) VALUES
('cami', 'ca@gmail.com', 'loro', 28, 1),
('luci', 'lu@gmail.com', 'camino', 30, 2);

INSERT INTO courses (title, description, level, teacher) VALUES
('React', 'In this course you will learn the concepts of React', 'basic', 1),
('Design', 'In this course you will learn the concepts of design', 'intermediate', 2);

INSERT INTO students_courses (student, course_id) VALUES
(1,2),
(2,1);

INSERT INTO categories (name) VALUES
('Desarrollo'),
('Design UX');

INSERT INTO courses_categories (course_id, category_id) VALUES
(1,1),
(2,2);

INSERT INTO course_videos (title, url, course_id) VALUES
('props', 'https://www.courses.com/React', 1),
('intro design', 'https://www.courses.com/Design', 2);